BankAccountsManagementSystem/Models/PersonneMorale.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace BankAccountsManagementSystem.Models
{
    public class PersonneMorale : Client
    {
        [Required]
        [RegularExpression("[0-9]{7}", ErrorMessage = "Le matricul fiscal doit contenir exactement 7 chiffres")]
        [Display(Name = "Matricul fiscal")]
        [Remote("IsMatriculFiscalAvailable", "MatriculFiscal", ErrorMessage = "Client existant")]
        public string MatriculFiscal { get; set; }
    }
}

BankAccountsManagementSystem/Controllers/ComptesController.cs
using System;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BankAccountsManagementSystem.DataAccessLayer;
using BankAccountsManagementSystem.Models;

namespace BankAccountsManagementSystem.Controllers
{
    public class ComptesController : Controller
    {
        private readonly BankDbContext _db = new BankDbContext();
        // GET: Comptes
        public ActionResult Index(string searchString)
        {
            try
            {
                var comptes = _db.Comptes.Include(c => c.Client);
                if (!String.IsNullOrEmpty(searchString))
                {
                    comptes = comptes.Where(c => c.Client.Id.ToString().Contains(searchString)
                                                 || c.CompteId.ToString().Contains(searchString)
                                                 || c.Type.ToString().Contains(searchString));
                }
                return View(comptes.ToList());
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Comptes/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var compte = _db.Comptes.Find(id);
                if (compte == null)
                {
                    return HttpNotFound();
                }
                return View(compte);
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Comptes/Create
        public ActionResult Create()
        {
            try
            {
                ViewBag.ClientId = new SelectList(_db.Clients, "Id", "Nom");
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Comptes/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CompteId,ClientId,Type,SoldeBase,DateOuverture")] Compte compte)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Comptes.Add(compte);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.ClientId = new SelectList(_db.Clients, "Id", "Nom", compte.ClientId);
                return View(compte);
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Comptes/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var compte = _db.Comptes.Find(id);
                if (compte == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ClientId = new SelectList(_db.Clients, "Id", "Nom", compte.ClientId);
                return View(compte);
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Comptes/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CompteId,ClientId,Type,SoldeBase,DateOuverture")] Compte compte)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Entry(compte).State = EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ClientId = new SelectList(_db.Clients, "Id", "Nom", compte.ClientId);
                return View(compte);
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        // GET: Comptes/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var compte = _db.Comptes.Find(id);
                if (compte == null)
                {
                    return HttpNotFound();
                }
                return View(compte);
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        // POST: Comptes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var compte = _db.Comptes.Find(id);
                _db.Comptes.Remove(compte);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        public ActionResult Error()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BankAccountsManagementSystem/Controllers/PersonneMoralesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BankAccountsManagementSystem.DataAccessLayer;
using BankAccountsManagementSystem.Models;

namespace BankAccountsManagementSystem.Controllers
{
    public class PersonneMoralesController : Controller
    {
        private readonly BankDbContext _db = new BankDbContext();
        // GET: PersonneMorales
        public ActionResult Index(string searchString)
        {
            try
            {
                var pm = from p in _db.PersonnesMorales
                    select p;

                if (!String.IsNullOrEmpty(searchString))
                {
                    pm = pm.Where(c => c.Nom.Contains(searchString)
                                       || c.MatriculFiscal.Contains(searchString));
                }
                return View(pm.ToList());
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        // GET: PersonneMorales/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var personneMorale = _db.PersonnesMorales.Find(id);
                if (personneMorale == null)
                {
                    return HttpNotFound();
                }
                return View(personneMorale);
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        // GET: PersonneMorales/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PersonneMorales/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nom,Adresse,MatriculFiscal")] PersonneMorale personneMorale)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Clients.Add(personneMorale);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(personneMorale);
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        // GET: PersonneMorales/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var personneMorale = _db.PersonnesMorales.Find(id);
                if (personneMorale == null)
                {
                    return HttpNotFound();
                }
                return View(personneMorale);
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        // POST: PersonneMorales/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nom,Adresse,MatriculFiscal")] PersonneMorale personneMorale)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Entry(personneMorale).State = EntityState.Modified;
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(personneMorale);
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        // GET: PersonneMorales/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var personneMorale = _db.PersonnesMorales.Find(id);
                if (personneMorale == null)
                {
                    return HttpNotFound();
                }
                return View(personneMorale);
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        // POST: PersonneMorales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var personneMorale = _db.PersonnesMorales.Find(id);
                _db.Clients.Remove(personneMorale);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        public ActionResult Error()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BankAccountsManagementSystem/Views/PersonneMorales/Create.cshtml
@model BankAccountsManagementSystem.Models.PersonneMorale

@{
    ViewBag.Title = "Créer";
}

<h2>Créer</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Personne morale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatriculFiscal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatriculFiscal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatriculFiscal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Créer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BankAccountsManagementSystem/Views/PersonneMorales/Delete.cshtml
@model BankAccountsManagementSystem.Models.PersonneMorale

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Vous êtes sur le point de supprimer ce client :</h3>
<div>
    <h4>Personne morale</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatriculFiscal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatriculFiscal)
        </dd>

    </dl>
    <h4>Voulez-vous continuer ?</h4>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retour à la liste", "Index")
        </div>
    }
</div>

BankAccountsManagementSystem/Views/PersonneMorales/Details.cshtml
@model BankAccountsManagementSystem.Models.PersonneMorale

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Personne morale</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatriculFiscal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatriculFiscal)
        </dd>

    </dl>
    @Html.ActionLink("Modifier les informations du client", "Edit", new {id = Model.Id})
</div>
<div>
    <br />
    <h4>Comptes</h4>
    <table class="table">
        <tr>
            <th>Numéro de compte</th>
            <th>Type</th>
            <th>Solde</th>
            <th>Date ouverture</th>
            <th></th>
        </tr>
        @foreach (var item in Model.Comptes)
        {
            <tr>
                <td>

                    @{
            var item1 = item;
                    }
                    @Html.DisplayFor(modelItem => item1.CompteId)
                </td>
                <td>

                    @{
            var item2 = item;
                    }
                    @Html.DisplayFor(modelItem => item2.Type)
                </td>
                <td>

                    @{
            var item3 = item;
                    }
                    @Html.DisplayFor(modelItem => item3.SoldeBase)
                </td>
                <td>

                    @{
            var item4 = item;
                    }
                    @Html.DisplayFor(modelItem => item4.DateOuverture)
                </td>
                <td>@Html.ActionLink("Modifier", "Edit", "Comptes", new { id = item.CompteId }, null) | @Html.ActionLink("Details", "Details", "Comptes", new { id = item.CompteId }, null)</td>
            </tr>
        }
    </table>
</div>

<p>
    @Html.ActionLink("Retour à la liste", "Index")
</p>

BankAccountsManagementSystem/Views/PersonneMorales/Edit.cshtml
@model BankAccountsManagementSystem.Models.PersonneMorale

@{
    ViewBag.Title = "Modifier";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Personne morale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatriculFiscal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatriculFiscal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatriculFiscal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvegarder" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BankAccountsManagementSystem/Views/PersonneMorales/Index.cshtml
@model IEnumerable<BankAccountsManagementSystem.Models.PersonneMorale>

@{
    ViewBag.Title = "Personnes morales";
}

<h2>Personnes morales</h2>

<p>
    @Html.ActionLink("Nouveau client", "Create")
</p>
@using (Html.BeginForm())
{
    <p>
        Rechercher : @Html.TextBox("SearchString")
        <input type="submit" value="Rechercher" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adresse)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MatriculFiscal)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Adresse)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MatriculFiscal)
        </td>
        <td>
            @Html.ActionLink("Modifier", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Supprimer", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>